# Generated by Django 3.0.7 on 2020-06-26 11:35

from django.db import migrations
import easy_thumbnails.fields
import shop_user.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopuser',
            options={'ordering': ('username',)},
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='avatar',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=shop_user.models.avatar_upload_directory, verbose_name='Avatar'),
        ),
    ]
