# Generated by Django 3.0.7 on 2020-06-18 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200618_1625'),
        ('usability', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
