# Generated by Django 3.0.7 on 2020-06-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usability', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Message')),
                ('created', models.DateTimeField(auto_now=True)),
                ('ip', models.GenericIPAddressField(verbose_name='Ip')),
            ],
            options={
                'verbose_name': 'Admin Message',
                'verbose_name_plural': 'Admin Messages',
                'ordering': ('created',),
                'unique_together': {('message', 'ip')},
            },
        ),
    ]
