# Generated by Django 3.0.7 on 2020-07-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usability', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmessage',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
