# Generated by Django 3.0.7 on 2020-06-17 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0001_initial'),
        ('usability', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usability.ProductCategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariantCharacteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.Characteristic')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductVariant')),
            ],
            options={
                'unique_together': {('product_variant', 'characteristic')},
            },
        ),
        migrations.AddField(
            model_name='productvariant',
            name='characteristics',
            field=models.ManyToManyField(blank=True, through='products.ProductVariantCharacteristic', to='reference.Characteristic'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='parent_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
