# Generated by Django 3.0.7 on 2020-06-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('sort_order',), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Ordering'),
        ),
    ]
