# Generated by Django 3.0.7 on 2020-06-26 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_auto_20200626_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-sort_order',), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('count', models.PositiveSmallIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_products', to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=70, verbose_name='Last Name')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('city', models.CharField(max_length=70, verbose_name='City')),
                ('street', models.CharField(max_length=70, verbose_name='Street')),
                ('building', models.CharField(max_length=50, verbose_name='Building')),
                ('phone', models.CharField(max_length=12, verbose_name='Phone')),
                ('post_code', models.CharField(blank=True, max_length=20, verbose_name='Post Code')),
                ('customer_notes', models.CharField(blank=True, max_length=250, verbose_name='Customer Notes')),
                ('manager_notes', models.CharField(blank=True, max_length=250, verbose_name='Manager Notes')),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('total_order_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('products', models.ManyToManyField(to='products.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
