# Generated by Django 3.0.7 on 2020-06-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200620_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discount price', max_digits=5, null=True, verbose_name='Sale price'),
        ),
    ]
