# Generated by Django 3.0.7 on 2020-07-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200707_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmeasure',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Measure category is not selected'), (1, 'Weight'), (2, 'Quantity'), (3, 'Length')], default=0, verbose_name='Measure Category'),
        ),
    ]
